### ISSUE TITLE
lifetime mismatch when tail type contains UnsafeCell

### ISSUE THREAD

**Issue by peku33** [joshua-maros/ouroboros#20]
If (so called) tailcontains UnsafeCell, or anything that internally contains UnsafeCell (like Mutex), following compiler error is generated:
```
mismatched types
expected reference `&'this devices::soft::surveillance::rtsp_recorder::hardware::test::Child<'this>`
   found reference `&'this devices::soft::surveillance::rtsp_recorder::hardware::test::Child<'static>`
...does not necessarily outlive the static lifetime
```
Minimal code to reproduce it:
```
use ouroboros::self_referencing;
use std::cell::UnsafeCell;

pub struct Child<'a> {
    child: UnsafeCell<&'a ()>,
}

pub struct Data {}

#[self_referencing]
struct Foo {
    data: Box<Data>,

    #[borrows(data)]
    #[covariant]
    child: Child<'this>,
}
```

Tested with 0.8.3 version, nightly compiler `1.52.0-nightly 2021-03-19`

**Comment by joshua-maros** [comment]
This is caused by the fact that `UnsafeCell` is not covariant. Adding the `#[covariant]` annotation implements additional methods which assume this property to be true for the particular variable. Since it is not, the compiler correctly generates an error.

**Comment by peku33** [comment]
So what is the correct way to have `Mutex` inside tail field and `borrow_*` methods available?

**Comment by joshua-maros** [comment]
Unfortunately, those methods require that the type is covariant to be able to work properly. If I recall correctly, the `with_FIELD` and `with` functions should still be generated even if the type is not covariant, so you can use those to access the data.

**Comment by peku33** [comment]
The case is a bit more complicated, because I need to return some data actually borrowing from field containing Mutex. This execatly requires `borrow_FIELD` function.

While inner representation of Mutex indeed consists of UnsafeCell, is the Mutex itself also invariant? If I get it correctly it's similar to `Option` or any other wrapper that is fine to be used with `covariant` attribtue. Does inner representation of the mutex indeed affects ability to have "borrow" from this field?

Maybe this can be sorted out, for example by:
- having `covariant_unsafe` attribute
- having unsafe borrow_* for such fields
- any other method that allows to borrow the data

**Comment by joshua-maros** [comment]
Yes, anything containing an UnsafeCell is itself invariant. An `UnsafeCell<'static>` cannot be changed to an `UnsafeCell<'smaller>`, so similarly a `Mutex<UnsafeCell<'static>>` cannot be changed to a `Mutex<UnsafeCell<'smaller>>`. If you could, someone could put a `'smaller` reference into the `UnsafeCell`, which could then be accessed after `'smaller` ends but `'static` is still valid, causing undefined behavior. If you really need to have it work in the way you describe then I don't think this crate could provide much help. I feel that adding a feature to add in explicitly unsafe methods for borrowing the data would not provide any benefits over writing it manually. The latter case may actually be better, as the implementation details are more obvious so it is more understandable what needs to be done to keep it safe.
