### ISSUE TITLE
Variance annotations required for non-borrowed fields

### ISSUE THREAD

**Issue by brendanzab** [joshua-maros/ouroboros#22]
For the following code:

```
#[ouroboros::self_referencing]
struct TraitObject {
    data0: Box<dyn std::fmt::Debug>,
    data1: Box<dyn std::fmt::Debug>,
    #[borrows(data0)]
    #[covariant]
    dref: &'this dyn std::fmt::Debug,
}
```

I get the following error:

```
error: Ouroboros cannot automatically determine if this type is covariant.

If it is covariant, it should be legal to convert any instance of that type to an instance of that type where all usages of 'this are replaced with a smaller lifetime. For example, Box<&'this i32> is covariant because it is legal to use it as a Box<&'a i32> where 'this: 'a. In contrast, Fn(&'this i32) cannot be used as Fn(&'a i32).

To resolve this error, add #[covariant] or #[not_covariant] to the field.

  --> fathom/src/driver.rs:42:12
   |
42 |     data1: Box<dyn std::fmt::Debug>,
   |            ^^^^^^^^^^^^^^^^^^^^^^^^
```

Is this intended? I would (naively) assume that non-borrowed fields would not need to have this clarified. At any rate, I can silence this error by adding `#[covariant]` annotations to the fields.

**Comment by joshua-maros** [comment]
Hm... I'm not entirely sure about this one. I'll do some more research when I have time but my thoughts are currently like this:
- Knowing whether or not a field is covariant is needed for generating the `borrow_*` methods, which are generated for most fields.
- However, the reason it is needed might not apply if the type does not use `'this`.
- However, there might not be a reliable way to detect if a type never uses `'this` and thus skip checking its covariance.

**Comment by joshua-maros** [comment]
Thinking about it more, any type where `'this` does not show up as a token should have nothing to do with `'this`. I've made the most recent version skip the covariance check for any field that meeets this condition.
