### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by fhoehle** [joshua-maros/ouroboros#24]
For packaging of downstream packages it would be nice to have a dedicated license which is used to gather all licenses of all depencies and repackage these license files.

**Comment by joshua-maros** [comment]
I had marked the project as dual-licensed under Apache 2 and MIT in the Cargo.toml files, I've now added the actual texts of those licenses so that they can be viewed outside of Crates.io. Both of these should impose only minimal licensing restrictions on downstream crates.

**Comment by fhoehle** [comment]
@joshua-maros many thanks for the fast action/reply. Would it be possible to add a license via the `license-file` vairable to the published crate? I can also provide a PR.

**Comment by joshua-maros** [comment]
My understanding was that the `license-file` variable should only be used if a non-standard license is being used.
