### ISSUE TITLE
Field privacy rules

### ISSUE THREAD

**Issue by meme** [joshua-maros/ouroboros#26]
After upgrading from "0.2" to "0.9" (since the previous versions were yanked), field privacy is not longer respected. In my code, I had used `pub(crate)` to access the `inner` field directly from an `impl VTIL`, however now it is permanently private. Adding `pub_extras` also does not resolve the issue.

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 74593b6..25f9184 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -100,11 +100,12 @@ mod arch_info;
 #[doc(hidden)]
 pub type Result<T> = std::result::Result<T, error::Error>;
 
-#[self_referencing(no_doc)]
 /// VTIL container
+#[self_referencing(no_doc)]
 pub struct VTIL<T: 'static> {
     source: Box<T>,
     #[borrows(source)]
+    #[covariant]
     pub(crate) inner: VTILInner<'this>,
     phantom: PhantomData<T>,
 }
```

The documentation mentions that `pub_extras` should be used in this case, is this a bug?

**Comment by meme** [comment]
Using `borrow_inner()` resolves the issue

**Comment by meme** [comment]
Is it possible to retrieve the `inner` field as a move rather than a borrow?

**Comment by joshua-maros** [comment]
Yes, IIRC there is a function `into_heads` that will allow you to move any non-self-referencing fields out of a self-referencing struct.

**Comment by meme** [comment]
Hmm, it seems like I can only access the borrowed field, `source`. Instead, I'd like to move the `inner` field: https://github.com/joshua-maros/ouroboros/pull/27

**Comment by joshua-maros** [comment]
That is what `into_heads` should allow you to do. Can you post a sample of what you want to do?

**Comment by meme** [comment]
Sure thing. The generated code for `into_heads` `drop`s the `self.inner` value which I am trying to retrieve:
```rust
            #[doc(hidden)]
            #[allow(clippy::drop_ref)]
            #[allow(clippy::drop_copy)]
            pub fn into_heads(self) -> Heads<T> {
                let phantom = self.phantom;
                ::core::mem::drop(self.inner);
                let source = self.source;
                Heads {
                    phantom,
                    source,
                    _consume_template_type_t: ::core::marker::PhantomData,
                }
            }
```
(from `cargo-expand`)

I want to write code like this: 
```rust
    /// Converts VTIL container into a byte vector, consuming the container
    pub fn into_bytes(self) -> Result<Vec<u8>> {
        let mut buffer = Vec::new();
        // For example, with `take_inner`:
        buffer.pwrite_with::<VTILInner>(self.take_inner(), 0, scroll::LE)?;
        Ok(buffer)
    }
```

**Comment by joshua-maros** [comment]
Since `inner` borrows `source`, it is not safe to move it. Rust lacks the syntax to properly express the lifetime requirements for doing that. The only thing I would suggest trying is to implement scroll::TryIntoCtx for VTIL instead of VTILInner so that you can pass the whole struct at once.

**Comment by meme** [comment]
Ok, will try that. Thank you for your help.
