### ISSUE TITLE
Suggestion: Rename `not_covariant` to `invariant`

### ISSUE THREAD

**Issue by jplatte** [joshua-maros/ouroboros#28]
From my understanding `not_covariant` in this library is only used for invariant types. Why not rename `not_covariant` to `invariant`?

cc https://github.com/Voultapher/self_cell/issues/10

**Comment by joshua-maros** [comment]
Actually, the existing name covers two cases, the second being types that
are contravariant. Both categories require the macro to avoid generating
the same set of methods.

**Comment by jplatte** [comment]
Are contravariant fields in a self-borrowing struct really useful / meaningful though? They wouldn't actually borrow from the owned part of the struct.

**Comment by joshua-maros** [comment]
As long as they *can* exist (fn(&self) is valid to have as a field), I
don't want to name the attribute in a way that excludes them. Even though I
can't imagine a situation where having a contravariant type would be
useful, it's still allowed by the language.

**Comment by jplatte** [comment]
Alright.
