### ISSUE TITLE
Lifetime mismatch if borrowing field is boxed

### ISSUE THREAD

**Issue by peku33** [joshua-maros/ouroboros#30]
Hi,

This issue started to occur after updating from version 0.8 to 0.9.

The following compiles on 0.8 and 0.9:
```
#[self_referencing(chain_hack)]
pub struct S2<'f> {
    r: Box<&'f ()>,

    #[borrows(r)]
    #[not_covariant]
    s1: &'this &'f (),
}
```

However if I wrap s1 field with Box:
```
#[self_referencing(chain_hack)]
pub struct S2<'f> {
    r: Box<&'f ()>,

    #[borrows(r)]
    #[not_covariant]
    s1: Box<&'this &'f ()>,
}
```

There is an error in 0.9 only:
```
in type `&'static &'f ()`, reference has a longer lifetime than the data it references the pointer is valid for the static lifetime rustc(E0491)
```

On 0.8 it compiles succesfully.

**Comment by joshua-maros** [comment]
Found the problem, looks like the logic for handling lifetime parameters wasn't being properly called in the (recently added) checks to make sure all uses `Box` refer to `std::Box` when using `chain_hack`.

The fix is now published under version `0.9.4`.
