### ISSUE TITLE
ouroboros leaks memory if a builder panics

### ISSUE THREAD

**Issue by Voultapher** [joshua-maros/ouroboros#31]
Given this program, and ouroboros 0.9:

```rust
use ouroboros::self_referencing;

#[self_referencing]
struct StringCell {
    owner: Box<String>,

    #[borrows(owner)]
    dependent: &'this String,
}

fn main() {
    let _ = StringCellBuilder {
        owner: Box::new("some string into".into()),
        dependent_builder: |_| todo!(),
    }
    .build();
}
```

And running it with miri:

```bash
$ cargo +nightly miri run
```

I get:

```
thread 'main' panicked at 'not yet implemented', src/main.rs:14:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
The following memory was leaked: alloc1433 (Rust heap, size: 16, align: 1) {
73 6f 6d 65 20 73 74 72 69 6e 67 20 69 6e 74 6f │ some string into
}
alloc1503 (Rust heap, size: 24, align: 8) {
0x00 │ ╾alloc1433[<untagged>]╼ 10 00 00 00 00 00 00 00 │ ╾──────╼........
0x10 │ 10 00 00 00 00 00 00 00                         │ ........
}

error: the evaluated program leaked memory

error: aborting due to previous error
```

Per se leaking is safe to do, but at least you should document it. I looked through the documentation and could not find any mention of it.

This came up in a discussion about self_cell and I've since revised my stance and switched from documenting the possible leak and providing an example that shows how to prevent it with catch_unwind, to handling the leak with a scope guard https://github.com/Voultapher/self_cell/commit/d4573008cdedbac20b20356167ee43b8cbce0cbe

**Comment by joshua-maros** [comment]
Thanks for bringing this up. For now I've added a note to the documentation for `0.9.5`, if I have some more time I'll look into how I can use the approach you linked to aovid this behavior altogether.

**Comment by joshua-maros** [comment]
This behavior no longer happens with versions after `0.10.0`, due to some changes in the constructor logic.

**Comment by Ten0** [comment]
Looks like the documentation still mentions this as happening 🤔
