### ISSUE TITLE
What's the use of stable_deref_trait?

### ISSUE THREAD

**Issue by mitsuhiko** [joshua-maros/ouroboros#58]
I noticed that the `Cargo.toml` references `stable_deref_trait`. But it looks like this is unused outside of an example.

**Comment by adamreichold** [comment]
I think that this is a left-over from when usage of the [`aliasable`](https://docs.rs/aliasable) crate was introduced: https://github.com/joshua-maros/ouroboros/commit/621e5b9a1a4e757fe28fa678cd0c101641fbe9e7

**Comment by alex** [comment]
I hadn't notice this issue, but my coincidence I'd sent https://github.com/joshua-maros/ouroboros/pull/59 earlier today.
