### ISSUE TITLE
Fallible builder?

### ISSUE THREAD

**Issue by SOF3** [joshua-maros/ouroboros#64]
How to create a borrowed field from a fallible method? For example,

```rs
#[self_referencing]
struct ArcMutexGuard {
    arc: Arc<Mutex<String>>,
    #[borrows(arc)] #[covariant]
    guard: MutexGuard<'this, String>,
}

let arc = Arc::default();
let guard = ArcMutexGuard {
    arc,
    guard_builder: |arc| arc.try_read(),
}
```

How can I pass out the `try_read()` error without storing a `Result` in the struct?

**Comment by Databean** [comment]
I had trouble finding this also, but the documentation mentions [two options](https://docs.rs/ouroboros/0.15.2/ouroboros/attr.self_referencing.html#mystructtry_newefields---resultmystruct-e) here.

- `MyStruct::try_new`
- `MyStructTryBuilder { ... }`

So in your case I assume it would be something like

```rust
let guard = ArcMutexGuardTryBuilder {
    arc,
    guard_builder: |arc| arc.try_read(),
}.build()?
```
