### ISSUE TITLE
please include license files in published crates

### ISSUE THREAD

**Issue by decathorpe** [joshua-maros/ouroboros#68]
I see that license files have been included after this issue was previously discussed here:
https://github.com/joshua-maros/ouroboros/issues/24

However, this hasn't resulted in these files being actually included in the .crate files and source code that is redistributed via crates.io.
Both the MIT and Apache-2.0 licenses terms require that redistributed sources contain a copy of the license text, so published crates also should / need to contained a copy of those files, as well.

It should be enough to create symbolic links from `LICENSE_MIT -> ../LICENSE_MIT` and `LICENSE_APACHE -> ../LICENSE_APACHE` in the `ouroboros` and `ouroboros_macro` subdirectories to have `cargo package` / `cargo publish` pick those up (unless you're running those commands from Windows, I think - there, you might need to use full copies).

**Comment by joshua-maros** [comment]
Thanks for bringing this to my attention, this should be fixed in `0.15.3`.

**Comment by decathorpe** [comment]
Awesome, thank you! 👍🏼
