### ISSUE TITLE
Docs should explain that `#[covariant]` cannot cause unsoundness

### ISSUE THREAD

**Issue by Aaron1011** [joshua-maros/ouroboros#72]
I was initially hesitant about adding `#[covariant] ` when prompted, since I hadn't checked if the type I was using was actually covariant over its lifetime. However, I discovered that incorrectly applying it (e.g. on a `RefCell` field) just results in a borrow check error in the generated method.

It would be good to explicitly mention this in the docs,  to avoid unnecessary worrying for users of this crate :)

**Comment by joshua-maros** [comment]
Thanks for pointing this out, the documentation has been updated.
