### ISSUE TITLE
Possibility to turn off the generated `new()` implementation

### ISSUE THREAD

**Issue by Qqwy** [joshua-maros/ouroboros#77]
I have some structs for which at construction time, the function(s) that are used to borrow from the 'normal' stuct field(s) are always the same.
And as per the documentation, using the builder over the generated `new` is recommended anyway.

As such, I'd like to provide my own new implementation that only takes the 'normal' struct fields as input parameters and internally uses the builder.

For the time being it is of course possible to rename the Ouroboros struct to a private struct (e.g. `struct MyTypeInner { ... }`) and wrap it by a public struct that contains it as its single struct field (e.g. `pub struct MyType(MyTypeInner)` ). But that seems more like a boilerplate-y workaround rather than a permanent solution.

I could not find an option to turn any part of the generated code off. Is this already possible, or would it require the addition of a new feature to ouroboros' macro?

**Comment by joshua-maros** [comment]
I recommend using the pattern you suggest, it is essentially the well-established "newtype" pattern. I believe using an existing pattern instead of introducing new features to the macro makes code easier to understand on a first viewing.
