### ISSUE TITLE
Allow 'static type parameters

### ISSUE THREAD

**Issue by Aaron1011** [joshua-maros/ouroboros#90]
I noticed that the latest version of ouroboros now prevents self-referential structs from containing any type parameters. Would it be sound to allow typr parameters with a `'static` bound (e.g. `struct MyStruct<T: 'static>`)?

**Comment by joshua-maros** [comment]
The current mechanism is incompatible with type parameters, but as I was writing an explanation I realized a fix for it. `0.17.0` will allow template parameters again.
