### ISSUE TITLE
Self-referencing struct with type parameter: type may not live long enough

### ISSUE THREAD

**Issue by muja** [joshua-maros/ouroboros#96]
Similar to my previous endeavour (#94), using type parameters for my docx struct makes it not compile:

```rust
use std::{collections::HashMap, io::Read};

use ouroboros::self_referencing;
use rc_zip::reader::sync::{EntryReader, HasCursor, SyncArchive};

#[self_referencing]
pub struct Docx<F: HasCursor + Read> {
    file: F,
    #[borrows(file)]
    #[covariant]
    arc: SyncArchive<'this, F>,
    #[borrows(arc)]
    #[covariant]
    readers: HashMap<String, xml::EventReader<EntryReader<<F as HasCursor>::Cursor<'this>>>>,
}
```

The error:

![image](https://github.com/joshua-maros/ouroboros/assets/3709726/deb357d8-fa5c-46b8-9b6d-f3d947544ef2)

This compiles fine if I remove the type parameter and replace `F` with `std::fs::File`.

**Comment by joshua-maros** [comment]
Add a `+ 'static` bound to the type parameter. If you need a custom lifetime, add a lifetime parameter `'a` and add `+ 'a` to the type parameter. Ouroboros does not support any other usage patterns at the moment.
