### ISSUE TITLE
Borrow mutably in an async context?

### ISSUE THREAD

**Issue by Einliterflasche** [joshua-maros/ouroboros#99]
Hey,
first of all thank you for this amazing crate! It really is dead-simple.

I'm sorry to ask this kinda basic question.

For example I need to do something like this:

```rust
#[self_referencing]
pub struct MyStruct {
    foo: Foo,
    #[borrows(mut foo)]
    #[covariant]
    bar: Bar<'this>,
}

impl MyStruct {
    async fn boo(self) {
        // ...
        self.borrow_bar_mut().async_method().await;
    }
}
```

There seems to be no `borrow_bar_mut` method, however, and `with_bar_mut`'s documentation states that no `borrow_bar_mut` was generated because the borrow checker can't guarantee that it's used safely. Does that mean there is currently no way to do what I want to do?

Thanks in advance :)

**Comment by joshua-maros** [comment]
You might be able to do something like `self.with_bar_mut(|bar| bar.async_method()).await`. If that doesn't work, there's no way to do what you want to do.

**Comment by Einliterflasche** [comment]
You're completely right - I tried to do that but misunderstood a type error from my code and thought this kinda thing doesn't work. This works. Thank you

**Comment by Daniel-Aaron-Bloom** [comment]
Just wanted to leave a comment here for the next person struggling with this when dealing with borrowing `Stream`s (possibly it can be generalized to other futures too).

```rust

// The borrowing stream you're trying to wrap
struct StreamItem;
struct StreamMaker;
async fn make_stream<'a>(_: &'a mut StreamMaker) -> Box<dyn 'a+Stream<Item=StreamItem>> {
    Box::new(stream::empty())
}

// The wrapper you're trying to make
#[ouroboros::self_referencing]
struct MyStruct {
    foo: StreamMaker,
    #[borrows(mut foo)]
    #[covariant]
    bar: Pin<Box<dyn Stream<Item = StreamItem> + 'this>>,
}

// The solution
impl Stream for MyStruct {
    type Item = StreamItem;
    fn poll_next(mut self: Pin<&mut Self>, cx: &mut task::Context<'_>) -> task::Poll<Option<Self::Item>> {
        self.with_bar_mut(|stream| {
            stream.poll_next_unpin(cx)
        })
    }
}

// Testing it out
async fn make() {
    let mut my_struct = MyStructAsyncBuilder{
        foo: StreamMaker,
        bar_builder: move |data: &mut StreamMaker| Box::pin(async move {
            let stream = make_stream(data).await;
            Box::into_pin(stream)
        }),
    }.build().await;

    // Hooray! We can stream now
    while let Some(_item) = my_struct.next().await {

    }
}
```
